/*
 * Copyright (c) 2013, Dwijesh Bhageerutty
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * * Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 * * Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */
package forms;

import qasp.QASP;

/**
 *
 * @author User
 */
public class QASPFrame extends javax.swing.JFrame {

    /**
     * Creates new form QASPFrame
     */
    public QASPFrame() {
        initComponents();
        setResizable(false);
        conversationPanel.getInputTextField().setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        statisticsPanel1 = new forms.StatisticsPanel();
        conversationPanel = new forms.ConversationPanel();
        conversationRepresentationPanel = new forms.ConversationRepresentationPanel();
        statisticsPanel = new forms.StatisticsPanel();
        menuBar = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        saveSessionMenuItem = new javax.swing.JMenuItem();
        loadSessionMenuItem = new javax.swing.JMenuItem();
        newSessionMenuItem = new javax.swing.JMenuItem();
        endSessionMenuItem = new javax.swing.JMenuItem();
        conversationMenu = new javax.swing.JMenu();
        endConversationMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        conversationPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        conversationRepresentationPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout conversationRepresentationPanelLayout = new javax.swing.GroupLayout(conversationRepresentationPanel);
        conversationRepresentationPanel.setLayout(conversationRepresentationPanelLayout);
        conversationRepresentationPanelLayout.setHorizontalGroup(
            conversationRepresentationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 316, Short.MAX_VALUE)
        );
        conversationRepresentationPanelLayout.setVerticalGroup(
            conversationRepresentationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        statisticsPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        file.setText("Session");

        saveSessionMenuItem.setText("Save Session");
        file.add(saveSessionMenuItem);

        loadSessionMenuItem.setText("Load Session");
        file.add(loadSessionMenuItem);

        newSessionMenuItem.setText("New Session");
        file.add(newSessionMenuItem);

        endSessionMenuItem.setText("End Session");
        endSessionMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endSessionMenuItemActionPerformed(evt);
            }
        });
        file.add(endSessionMenuItem);

        menuBar.add(file);

        conversationMenu.setText("Conversation");

        endConversationMenuItem.setText("End Conversation");
        conversationMenu.add(endConversationMenuItem);

        menuBar.add(conversationMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(statisticsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(conversationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(conversationRepresentationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(conversationRepresentationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(conversationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(statisticsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void endSessionMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endSessionMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_endSessionMenuItemActionPerformed

    public StatisticsPanel getStatisticsPanel() {
        return statisticsPanel;
    }

    public ConversationPanel getConversationPanel() {
        return conversationPanel;
    }

    public ConversationRepresentationPanel getConversationRepresentationPanel() {
        return conversationRepresentationPanel;
    }

    /**
     * @return the loadSessionMenuItem
     */
    public javax.swing.JMenuItem getLoadSessionMenuItem() {
        return loadSessionMenuItem;
    }

    /**
     * @return the saveSessionMenuItem
     */
    public javax.swing.JMenuItem getSaveSessionMenuItem() {
        return saveSessionMenuItem;
    }

    /**
     * @return the endSessionMenuItem
     */
    public javax.swing.JMenuItem getEndSessionMenuItem() {
        return endSessionMenuItem;
    }

    /**
     * @return the newSessionMenuItem
     */
    public javax.swing.JMenuItem getNewSessionMenuItem() {
        return newSessionMenuItem;
    }

    /**
     * @return the endConversationMenuItem
     */
    public javax.swing.JMenuItem getEndConversationMenuItem() {
        return endConversationMenuItem;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu conversationMenu;
    private forms.ConversationPanel conversationPanel;
    private forms.ConversationRepresentationPanel conversationRepresentationPanel;
    private javax.swing.JMenuItem endConversationMenuItem;
    private javax.swing.JMenuItem endSessionMenuItem;
    private javax.swing.JMenu file;
    private javax.swing.JMenuItem loadSessionMenuItem;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem newSessionMenuItem;
    private javax.swing.JMenuItem saveSessionMenuItem;
    private forms.StatisticsPanel statisticsPanel;
    private forms.StatisticsPanel statisticsPanel1;
    // End of variables declaration//GEN-END:variables
}
