/*
 * Copyright (c) 2013, Dwijesh Bhageerutty
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * * Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 * * Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */
package forms;

/**
 *
 * @author User
 */
public class StatisticsPanel extends javax.swing.JPanel {

    /**
     * Creates new form DataPanel
     */
    public StatisticsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        convoStartTimeLabel = new javax.swing.JLabel();
        convoStartTimeTextField = new javax.swing.JTextField();
        conversationDurationLabel = new javax.swing.JLabel();
        conversationDurationTextField = new javax.swing.JTextField();
        sessionIdLabel = new javax.swing.JLabel();
        sessionIdTextField = new javax.swing.JTextField();
        noOfConversationLabel = new javax.swing.JLabel();
        noOfConversationTextField = new javax.swing.JTextField();
        sessionLabel = new javax.swing.JLabel();
        convoLabel = new javax.swing.JLabel();
        noOfNodesLabel = new javax.swing.JLabel();
        noOfNodesTextField = new javax.swing.JTextField();
        noOfNodesLabelConvo = new javax.swing.JLabel();
        noOfNodesTextFieldConvo = new javax.swing.JTextField();
        sessionStartDateLabel = new javax.swing.JLabel();
        sessionStartDateTextField = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(340, 399));

        convoStartTimeLabel.setText("Conversation Start Time: ");

        convoStartTimeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convoStartTimeTextFieldActionPerformed(evt);
            }
        });

        conversationDurationLabel.setText("Conversation Duration: ");

        sessionIdLabel.setText("Session Id: ");

        noOfConversationLabel.setText("No. of Conversations: ");

        sessionLabel.setText("Session:");

        convoLabel.setText("Conversation:");

        noOfNodesLabel.setText("No. of Nodes: ");

        noOfNodesLabelConvo.setText("No. of Nodes: ");

        sessionStartDateLabel.setText("Start Date: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sessionLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sessionIdLabel)
                            .addComponent(noOfConversationLabel)
                            .addComponent(noOfNodesLabel)
                            .addComponent(sessionStartDateLabel))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sessionStartDateTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                            .addComponent(noOfNodesTextField)
                            .addComponent(noOfConversationTextField)
                            .addComponent(sessionIdTextField)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(conversationDurationLabel)
                            .addComponent(noOfNodesLabelConvo)
                            .addComponent(convoStartTimeLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(conversationDurationTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(convoStartTimeTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                            .addComponent(noOfNodesTextFieldConvo)))
                    .addComponent(convoLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sessionLabel)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(noOfConversationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(noOfConversationLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(noOfNodesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(noOfNodesLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sessionStartDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sessionStartDateLabel)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sessionIdLabel)
                        .addComponent(sessionIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(convoLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(convoStartTimeLabel)
                    .addComponent(convoStartTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conversationDurationLabel)
                    .addComponent(conversationDurationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noOfNodesLabelConvo)
                    .addComponent(noOfNodesTextFieldConvo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void convoStartTimeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convoStartTimeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_convoStartTimeTextFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel conversationDurationLabel;
    private javax.swing.JTextField conversationDurationTextField;
    private javax.swing.JLabel convoLabel;
    private javax.swing.JLabel convoStartTimeLabel;
    private javax.swing.JTextField convoStartTimeTextField;
    private javax.swing.JLabel noOfConversationLabel;
    private javax.swing.JTextField noOfConversationTextField;
    private javax.swing.JLabel noOfNodesLabel;
    private javax.swing.JLabel noOfNodesLabelConvo;
    private javax.swing.JTextField noOfNodesTextField;
    private javax.swing.JTextField noOfNodesTextFieldConvo;
    private javax.swing.JLabel sessionIdLabel;
    private javax.swing.JTextField sessionIdTextField;
    private javax.swing.JLabel sessionLabel;
    private javax.swing.JLabel sessionStartDateLabel;
    private javax.swing.JTextField sessionStartDateTextField;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the conversationDurationTextField
     */
    public javax.swing.JTextField getConversationDurationTextField() {
        return conversationDurationTextField;
    }

    /**
     * @return the convoStartTimeTextField
     */
    public javax.swing.JTextField getConvoStartTimeTextField() {
        return convoStartTimeTextField;
    }

    /**
     * @return the noOfConversationTextField
     */
    public javax.swing.JTextField getNoOfConversationTextField() {
        return noOfConversationTextField;
    }

    /**
     * @return the noOfNodesTextField
     */
    public javax.swing.JTextField getNoOfNodesTextField() {
        return noOfNodesTextField;
    }

    /**
     * @return the noOfNodesTextFieldConvo
     */
    public javax.swing.JTextField getNoOfNodesTextFieldConvo() {
        return noOfNodesTextFieldConvo;
    }

    /**
     * @return the sessionIdTextField
     */
    public javax.swing.JTextField getSessionIdTextField() {
        return sessionIdTextField;
    }

    /**
     * @return the sessionStartDateTextField
     */
    public javax.swing.JTextField getSessionStartDateTextField() {
        return sessionStartDateTextField;
    }
}
